name: workstation_env
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - psutil=5.9.0
  - pip:
    - pandas==2.0.2
    - scikit-learn==1.2.2
    - mlflow==2.4.1
    - mlflow-skinny==2.4.1
    - azureml-mlflow==1.51.0
    - matplotlib==3.7.1
